--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/AwaitForm
build-by-default: true
branches:
- master
projects:
  AwaitForm:
    path: ""
    model: virion
    type: library
...
